version: '3'
services:
  mypostgresmovies:
    image: postgres
    restart: always
    container_name: mypostgresmovies
    networks:
        amazingmovies:
          ipv4_address: 173.20.128.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amazingmovies
  amazingmovies-api:
    depends_on:
      - mypostgresmovies
    build: 
      context: ./amazingmovies-api
      dockerfile: Dockerfile
    container_name: amazingmovies-api
    networks:
       amazingmovies:
        ipv4_address: 173.20.128.2
    restart: always
    links:
      - mypostgresmovies
    restart: always
    ports:
      - 8081:8081
  amazingmovies-ui:
    depends_on:
      - amazingmovies-api
    container_name: amazingmovies-ui
    build:
      context: ./amazingmovies-ui
      dockerfile: Dockerfile
    networks:
      amazingmovies:
        ipv4_address: 173.20.128.4
    restart: always
    ports:
      - 80:80

networks:
  amazingmovies:
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/16